import React from "react";

export default function TermsOfUse() {
  return (
    <div className="container py-5 page-fade-in">
      <div className="glass-panel p-4 p-md-5" style={{ maxWidth: 900, margin: "0 auto" }}>
        <h1 className="mb-2">Terms of Use</h1>
        <p style={{ color: "var(--color-text-muted)" }}>Last updated: September 20, 2026</p>

        <p>
          Welcome to ReadMe. By accessing or using this website, you agree to be bound by these
          Terms of Use. If you do not agree, please do not use the Site.
        </p>

        <h4 className="mt-4">1. Description of Service</h4>
        <p>
          ReadMe is a website for reading illustrated storybooks. Content on this Site, including
          text and illustrations, is generated with the assistance of artificial intelligence
          tools.
        </p>

        <h4 className="mt-4">2. AI-Generated Content Disclaimer</h4>
        <p>
          Stories, character illustrations, and cover art on this Site are created using
          AI-generation tools. We make no claim of exclusive originality over this content, and
          similar or identical content may exist elsewhere, including content generated by other
          users of the same AI tools. Content is provided "as is" for entertainment and reading
          purposes only.
        </p>

        <h4 className="mt-4">3. Permitted Use</h4>
        <p>You may use this Site for personal, non-commercial reading only. You may not:</p>
        <ul>
          <li>Copy, reproduce, redistribute, or republish content from this Site elsewhere</li>
          <li>Scrape, bulk-download, or systematically extract content or data from the Site</li>
          <li>Use automated tools (bots, scripts) to access the Site beyond normal browsing</li>
          <li>Attempt to circumvent security measures, including rate limiting or authentication</li>
          <li>Use the Site for any unlawful purpose</li>
        </ul>

        <h4 className="mt-4">4. User Accounts</h4>
        <p>
          You must provide accurate information when creating an account and are responsible for
          maintaining the confidentiality of your password and all activity under your account.
          You must notify us promptly of any unauthorized use of your account. This Site is not
          intended for use by children under 13.
        </p>

        <h4 className="mt-4">5. Advertising</h4>
        <p>
          This Site may display third-party advertisements, including through Google AdSense.
          We are not responsible for the content of advertisements shown, or for any products or
          services offered by advertisers.
        </p>

        <h4 className="mt-4">6. Intellectual Property</h4>
        <p>
          The ReadMe name, logo, site design, and underlying software are the property of the Site
          operator. This does not extend to the AI-generated story content itself, as described in
          Section 2.
        </p>

        <h4 className="mt-4">7. Disclaimer of Warranties</h4>
        <p>
          This Site is provided "as is" and "as available," without warranties of any kind, express
          or implied. We do not guarantee the Site will be uninterrupted, error-free, or secure.
        </p>

        <h4 className="mt-4">8. Limitation of Liability</h4>
        <p>
          To the fullest extent permitted by law, the Site operator shall not be liable for any
          indirect, incidental, or consequential damages arising from your use of, or inability to
          use, this Site.
        </p>

        <h4 className="mt-4">9. Termination</h4>
        <p>
          We may suspend or terminate your access to the Site at our discretion, including for
          violation of these Terms, without prior notice.
        </p>

        <h4 className="mt-4">10. Changes to These Terms</h4>
        <p>
          We may revise these Terms at any time. Continued use of the Site after changes are
          posted constitutes acceptance of the revised Terms.
        </p>

        <h4 className="mt-4">11. Governing Law</h4>
        <p>These Terms are governed by the laws of India, Maharastra</p>

        <h4 className="mt-4">12. Contact Us</h4>
        <p>Questions about these Terms can be sent to: <strong>abhishekkhursange139@gmail.com</strong></p>
      </div>
    </div>
  );
}